var json_language = {
    english: {
        _init_settings_: "Startup settings",
        _personal_data_: "Personal data",
        _personal_data_explain_: "Your last saved data should automatically be filled in, or you can copy-paste a backup file here.<br><i>*For new users only: Leave Empty</i>",
        _master_data_: "Master data",
        _master_data_explain_: "Master data is loaded from the server, if the loading is slow, then please wait for \"Loaded!\" to appear in the text box.",
        _color_settings_: "Color settings",
        _color_normal_: "Normal",
        _color_dark_: "Dark",
        _language_settings_: "Language settings",
        _start_tool_: "Start GCS tool",
        _search_: "Search",
        _templates_: "Templates",
        _manual_: "Manual",
        _ccontact_: "Company Contact",
        _assistant_: "Assistant",
        _edit_: "Edit",
        _save_load_: "Save/Load",
        _need_save_: "Need to save personal data",
        _input_: "Input:",
        _add_: "Add",
        _clear_: "Clear",
        _remove_last_: "Remove last word",
        _s_search_: "Special search",
        _master_copy_: "Copied master data",
        _new_: "*NEW*",
        _request_: "Request",
        _s_label_: "Shipping label",
        _s_invoice_: "Invoice",
        _s_label_invoice_: "Shipping label/Invoice",
        _show_: "Show",
        _find_: "Find",
        _find_order_mail_: "Find order number/email",
        _external_: "External links",
        _search_result_: "Search result",
		_personal_: "Personal",
		_share_: "Share",
		_master_: "Master",
		_login_: "Login",
		_change_settings_: "Change Settings",
		_new_template_: "New Template",
		_new_manual_: "New Manual",
		_new_ccontact_: "New Company Contact",
		_new_asistant_: "New Assistant",
		_user_id_: "User ID",
		_team_: "Team",
		_interface_: "Interface",
		_style_: "Style",
		_lang_priority: "Language priority",
		_language_: "Language",
		_priority_: "Priority",
		_reminders_: "Reminders",
		_unique_id_: "Unique ID",
		_type_: "Type",
		_category_: "Category",
		_last_updated_: "Last Updated",
		_title_: "Title:",
		_delete_: "Delete",
		_save_content_: "Save content",
		_share_data_: "Share data",
		_load_data_: "Load data",
		_data_: "Data",
		_approve_master_: "Approve as master data",
		_process_: "Process",
		_process_share_: "Process Share",
		_process_load_: "Process Load",
		_save_pd_explain_: "Whenever you add any content or change any settings you will need to re-save your own personal data",
		_save_pd_process_: "<b>1.</b>Press the \"Personal data\" button<br><b>2.</b>The data will automatically be saved to your browser<br><b>3.</b>(Optional) Copy-Paste the data below to a backup file on your computer",
		_save_sd_explain_: "Share data is used for sharing templates and manuals that you have created",
		_save_sd_share_process_: "<b>1.</b>Share the template/manual with your team for confirming that it is acceptable and that no one opose to add it to the master data<br><b>2.</b>If there are any issues, review the template/manual and start over at step 1, otherwise proceed with step 3<br><b>3.</b>Press the \"Share data\" button<br><b>4.</b>Select the templates/manuals that you want to share and press \"Generate data\"<br><b>5.</b>Copy paste all the text in the text box to a textfile on your computer<br><b>6.</b>Share the file with the person responsible to update the master data",
		_save_sd_load_process_: "<b>1.</b>Copy paste the shared data in the text box below<br><b>2.</b>Press \"Load data\"",
		_save_md_explain_: "Master data is used for shared data that all users should use (official approved data)",
		_save_md_process_: "<b>1.</b>Press the \"Master data\" button<br><b>2.</b>Copy-Paste all the text in the text box to the \"Master.txt\" textfile on the server",
		_save_explain_: "*Copy paste to data file and save the file!",
		_approve_m_: "Approve (Master)",
		_approve_p_: "Approve (Private)",
		_reject_: "Reject",
		_process_approve_: "Approval process",
		_approve_process_: "<b>1.</b>Press the \"Approve (Master)\" button to approve the data as master data (Should only be used if the data follows our current rules, in all other cases it is nessesary to get approval for the process beforehand)<br><b>2.</b>Press the \"Approve (Private)\" button to add the data as private data (Use this if further confirmation is needed)<br><b>3.</b>Press the \"Reject\" button to avoid any changes (Should be used if there is any problems with the suggested data that needs to be fixed)",
		_back_: "Back",
		_save_: "SAVE",
		_title_: "Title",
		_subtitle_: "Subtitle",
		_new_line_: "New line",
		_divider_: "Divider line",
		_background_: "Background",
		_text_color_: "Textcolor",
		_table_: "Table",
		_dot_list_: "Dot list",
		_num_list_: "Number list",
		_list_element_: "List element",
		_image_: "Image",
		_search_btn_: "Search button",
		_add_question_: "Add question",
		_add_answer_: "Add answer",
		_view_all_: "View all *SLOW*"
    },
    japanese: {
        _init_settings_: "初期設定",
        _personal_data_: "個人データ",
        _personal_data_explain_: "一番最近セーブしたデータは自動的に記入される、そしてバックアップデータのコピーペーストも可能です。<br><i>※新しいユーザーのみ：空にしてください。</i>",
        _master_data_: "マスターデータ",
        _master_data_explain_: "マスターデータファイルはサーバから取得する、もし遅かったら、テクストボックスに「ロード済み！」が表示されるまでお待ちください。",
        _color_settings_: "カラー設定",
        _color_normal_: "普通",
        _color_dark_: "ダーク",
        _language_settings_: "言語設定",
        _start_tool_: "GCSツールを開始",
        _search_: "検索",
        _templates_: "テンプレート",
        _manual_: "マニュアル",
        _ccontact_: "会社連絡",
        _assistant_: "サポート",
        _edit_: "編集",
        _save_load_: "保存・ロード",
        _need_save_: "個人データをセーブする必要有り",
        _input_: "入力：",
        _add_: "追加",
        _clear_: "クレア",
        _remove_last_: "最後削除",
        _s_search_: "特殊検索",
        _master_copy_: "マスターコピー",
        _new_: "*新しい*",
        _request_: "依頼",
        _s_label_: "ラベル",
        _s_invoice_: "インボイス",
        _s_label_invoice_: "ラベル・インボイス",
        _show_: "表示",
        _find_: "見つけ",
        _find_order_mail_: "注文番号・メール見つけ",
        _external_: "外部リンク",
        _search_result_: "検索結果",
		_personal_: "個人",
		_share_: "共有",
		_master_: "マスター",
		_login_: "ログイン",
		_change_settings_: "設定変更",
		_new_template_: "新規テンプレート",
		_new_manual_: "新規マニュアル",
		_new_ccontact_: "新規会社連絡",
		_new_asistant_: "新規サポート",
		_user_id_: "ユーザーID",
		_team_: "チーム",
		_interface_: "インターフェイス",
		_style_: "スタイル",
		_lang_priority: "言語優先",
		_language_: "言語",
		_priority_: "優先",
		_reminders_: "リマインダ",
		_unique_id_: "ユニックID",
		_type_: "種類",
		_category_: "カテゴリー",
		_last_updated_: "最新更新",
		_title_: "タイトル：",
		_delete_: "削除",
		_save_content_: "コンテンツ保存",
		_share_data_: "共有データ",
		_load_data_: "データロード",
		_data_: "データ",
		_approve_master_: "マスターデータ承認",
		_process_: "処理",
		_process_share_: "共有処理",
		_process_load_: "ロード処理",
		_save_pd_explain_: "データ内容を追加したり、設定を変更したりするときに再度個人データを保存する必要があります",
		_save_pd_process_: "<b>1.</b>「個人データ」ボタンを押す<br><b>2.</b>データが自動的にブラウザに保存される<br><b>3.</b>（任意）テキストボクスの内容を自分のコンピューターのバックアップファイルにコピーペーストする",
		_save_sd_explain_: "共有のデータは自分が作成したテンプレート・マニュアルを共有するときに使う",
		_save_sd_share_process_: "<b>1.</b>チーム内でテンプレート・マニュアルを共有して、問題が無いか・マスターデータに追加する反対が無いかを確認する<br><b>2.</b>もし問題があったら、問題点を修正してステップ１に戻る、他の場合にはステップ３で続く<br><b>3.</b>「共有データ」ボタンを押す<br><b>4.</b>共有したテンプレート・マニュアルを選択し、「データ作成」を押す<br><b>5.</b>テキストボクスの内容を自分のコンピューターのテキストファイルにコピーペーストする<br><b>6.</b>作成したファイルをマスターデータを更新するスタッフに渡す",
		_save_sd_load_process_: "<b>1.</b>共有されたデータを下記のテキストボクスにコピーペーストする<br><b>2.</b>「データロード」を押す",
		_save_md_explain_: "マスターのデータはみんなが使うものになります（正式的に認められているデータ）",
		_save_md_process_: "<b>1.</b>「マスタデータ」ボタンを押す<br><b>2.</b>テキストボクスの内容をサーバーの「Master.txt」のテキストファイルにコピーペーストする",
		_save_explain_: "※データファイルにコピーペーストしてください。",
		_approve_m_: "承認（マスター）",
		_approve_p_: "承認（個人）",
		_reject_: "拒否",
		_process_approve_: "承認処理",
		_approve_process_: "<b>1.</b>「承認」ボタンを押すと、データがマスターデータとして追加されます（今のルールに従っているものにしか使えない、その他の場合には、先ず処理方法の承認が必要）<br><b>2.</b>「承認（個人）」ボタンを押すと、個人データとして追加されます（もしまだ承認・確認が必要な場合には、こちらを使ってください）<br><b>3.</b>「拒否」ボタンを押すと、何も変わらない（もし修正が必要な問題があったら、こちらを使ってください）",
		_back_: "戻る",
		_save_: "保存",
		_title_: "タイトル",
		_subtitle_: "サブタイトル",
		_new_line_: "改行",
		_divider_: "垂直線",
		_background_: "背景",
		_text_color_: "フォント色",
		_table_: "テーブル",
		_dot_list_: "ドットリスト",
		_num_list_: "番号リスト",
		_list_element_: "リスト",
		_image_: "画像",
		_search_btn_: "検索ボタン",
		_add_question_: "質問追加",
		_add_answer_: "答え追加",
		_view_all_: "全部表示 *遅い*"
    },
    swedish: {
        _init_settings_: "Starta inställningar",
        _personal_data_: "Personlig data",
        _personal_data_explain_: "Din senaste sparade data fylls in automatiskt, men du kan också kopiera-klistra in säkerhets sparad data.<br><i>*För nya användare: Lämna tom</i>",
        _master_data_: "Mästar data",
        _master_data_explain_: "Mästar data laddas ner från servern, om nerladdningen är långsam, vänta på att \"Laddad!\" dycker up i text rutan.",
        _color_settings_: "Färg inställningar",
        _color_normal_: "Normal",
        _color_dark_: "Mörk",
        _language_settings_: "Språk inställningar",
        _start_tool_: "Starta GCS verktyget",
        _search_: "Sök",
        _templates_: "Mallar",
        _manual_: "Manual",
        _ccontact_: "Företags Kontakt",
        _assistant_: "Assistent",
        _edit_: "Ändra",
        _save_load_: "Spara/Ladda",
        _need_save_: "Behöver spara personlig data",
        _input_: "Inmatning:",
        _add_: "Lägg till",
        _clear_: "Rensa",
        _remove_last_: "Ta bort sista ord",
        _s_search_: "Speciel sök",
        _master_copy_: "Mästar kopia data",
        _new_: "*NY*",
        _request_: "Begär",
        _s_label_: "Fraktetikett",
        _s_invoice_: "Faktura",
        _s_label_invoice_: "Fraktetikett/Faktura",
        _show_: "Visa",
        _find_: "Hitta",
        _find_order_mail_: "Hitta ordernummer/epost",
        _external_: "Externa länkar",
        _search_result_: "Sök resultat",
		_personal_: "Personlig",
		_share_: "Dela",
		_master_: "Mästar",
		_login_: "Logga in",
		_change_settings_: "Ändra inställningar",
		_new_template_: "Ny mall",
		_new_manual_: "Ny manual",
		_new_ccontact_: "Ny Företag Kontakt",
		_new_asistant_: "Ny Assistent",
		_user_id_: "Användar ID",
		_team_: "Grupp",
		_interface_: "Gränssnitt",
		_style_: "Stil",
		_lang_priority: "Språk prioritering",
		_language_: "Språk",
		_priority_: "Prioritet",
		_reminders_: "Påminnelser",
		_unique_id_: "Unikt ID",
		_type_: "Typ",
		_category_: "Kategori",
		_last_updated_: "Senast updaterad",
		_title_: "titel:",
		_delete_: "Radera",
		_save_content_: "Spara innehåll",
		_share_data_: "Dela data",
		_load_data_: "Ladda data",
		_data_: "Data",
		_approve_master_: "Godkänn som mästar data",
		_process_: "Bearbeta",
		_process_share_: "Bearbeta Dela",
		_process_load_: "Bearbeta Ladda",
		_save_pd_explain_: "#SWE#Whenever you add any content or change any settings you will need to re-save your own personal data",
		_save_pd_process_: "#SWE#<b>1.</b>Press the \"Personal data\" button<br><b>2.</b>The data will automatically be saved to your browser<br><b>3.</b>(Optional) Copy-Paste the data below to a backup file on your computer",
		_save_sd_explain_: "#SWE#Share data is used for sharing templates and manuals that you have created",
		_save_sd_share_process_: "#SWE#<b>1.</b>Share the template/manual with your team for confirming that it is acceptable and that no one opose to add it to the master data<br><b>2.</b>If there are any issues, review the template/manual and start over at step 1, otherwise proceed with step 3<br><b>3.</b>Press the \"Share data\" button<br><b>4.</b>Select the templates/manuals that you want to share and press \"Generate data\"<br><b>5.</b>Copy paste all the text in the text box to a textfile on your computer<br><b>6.</b>Share the file with the person responsible to update the master data",
		_save_sd_load_process_: "#SWE#<b>1.</b>Copy paste the shared data in the text box below<br><b>2.</b>Press \"Load data\"",
		_save_md_explain_: "#SWE#Master data is used for shared data that all users should use (official approved data)",
		_save_md_process_: "#SWE#<b>1.</b>Press the \"Master data\" button<br><b>2.</b>Copy-Paste all the text in the text box to the \"Master.txt\" textfile on the server",
		_save_explain_: "*Kopiera och klistra in data i fil att spara!",
		_approve_m_: "Godkänn (Mästar)",
		_approve_p_: "Godkänn (Privat)",
		_reject_: "Avstå",
		_process_approve_: "Godkänn bearbeta",
		_approve_process_: "#SWE#<b>1.</b>Press the \"Approve (Master)\" button to approve the data as master data (Should only be used if the data follows our current rules, in all other cases it is nessesary to get approval for the process beforehand)<br><b>2.</b>Press the \"Approve (Private)\" button to add the data as private data (Use this if further confirmation is needed)<br><b>3.</b>Press the \"Reject\" button to avoid any changes (Should be used if there is any problems with the suggested data that needs to be fixed)",
		_back_: "Tillbaka",
		_save_: "SPARA",
		_title_: "Titel",
		_subtitle_: "Undertitel",
		_new_line_: "Ny rad",
		_divider_: "Avdelnings linie",
		_background_: "Bakgrund",
		_text_color_: "Textfärg",
		_table_: "Tabell",
		_dot_list_: "Punkt lista",
		_num_list_: "Nummer lista",
		_list_element_: "Listelement",
		_image_: "Bild",
		_search_btn_: "Sök knapp",
		_add_question_: "Lägg till fråga",
		_add_answer_: "Lägg till svar",
		_view_all_: "Visa alla *LÅNGSAM*"
    }
}

function UpdateLanguage(source) {
    var language_id = document.getElementById(source).value;
    var z = document.getElementsByTagName("*");

    for (var i = 0; i < z.length; i++) {
        var elmnt = z[i];
        var lval = elmnt.getAttribute("lg_language");
        if (lval) {
            elmnt.innerHTML = json_language[language_id][lval];
        }
    }
}
UpdateLanguage("lg_language");