module.exports = (sequelize, type) => sequelize.define('irelandtaricjob', {
  id: { type: type.STRING(32), primaryKey: true },
  owner: { type: type.STRING(32), allowNull: false },
  input: { type: type.JSON, allowNull: false },
  digest: type.STRING(64),
  upstreamId: type.STRING(32),
  state: { type: type.STRING(24), allowNull: false, defaultValue: 'queued' },
  output: type.JSON,
  error: type.STRING(64),
  selectedCode: type.STRING(10),
  feedback: { type: type.STRING(24), allowNull: false, defaultValue: 'none' },
  attempts: { type: type.INTEGER, allowNull: false, defaultValue: 0 },
  polls: { type: type.INTEGER, allowNull: false, defaultValue: 0 },
  resumes: { type: type.INTEGER, allowNull: false, defaultValue: 0 },
  nextAt: { type: type.DATE, allowNull: false },
  expiresAt: { type: type.DATE, allowNull: false },
  leaseUntil: type.DATE,
  leaseOwner: type.STRING(32),
}, { indexes: [{ fields: ['state', 'nextAt'] }, { fields: ['owner', 'createdAt'] }, { fields: ['expiresAt'] }] });
